# Generated by Django 3.0.4 on 2020-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_item', models.CharField(max_length=200)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
